#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.d"

#=================================================
# BACKUP THE PHP-FPM CONFIGURATION
#=================================================

if [ $php_version != "none" ]
then
    ynh_backup "/etc/php/${php_version}/fpm/pool.d/$app.conf"
fi

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================

if [ $database != "none" ]
then
    ynh_print_info "Backing up the database..."

    if [ $database == "mysql" ]; then
        ynh_mysql_dump_db > db.sql*
    elif [ $database == "postgresql" ]; then
        ynh_psql_dump_db > db.sql
    fi
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
